/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.merci.apresentacao;

import br.edu.ifnmg.merci.entidade.GrupoUsuarios;
import br.edu.ifnmg.merci.entidade.Usuario;
import br.edu.ifnmg.merci.excecao.UsuarioCampoLoginVazioException;
import br.edu.ifnmg.merci.excecao.UsuarioCampoNomeVazioException;
import br.edu.ifnmg.merci.excecao.UsuarioCampoSenhaVazioException;
import br.edu.ifnmg.merci.excecao.UsuarioCaractereInvalidoLogin;
import br.edu.ifnmg.merci.excecao.UsuarioCaractereInvalidoSenhaException;
import br.edu.ifnmg.merci.excecao.UsuarioException;
import br.edu.ifnmg.merci.excecao.UsuarioGrupoNaoSelecionadoException;
import br.edu.ifnmg.merci.excecao.UsuarioLoginGrandeException;
import br.edu.ifnmg.merci.excecao.UsuarioNaoEncontradoException;
import br.edu.ifnmg.merci.excecao.UsuarioNomeGrandeException;
import br.edu.ifnmg.merci.excecao.UsuarioPesquisaInvalidaException;
import br.edu.ifnmg.merci.excecao.UsuarioSenhaGrandeException;
import br.edu.ifnmg.merci.negocio.UsuarioBO;
import br.edu.ifnmg.merci.negocio.UsuarioGrupoUsuarioBO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexBruno
 */
public class TelaUsuariosForm extends javax.swing.JFrame {

    private Usuario usuario = new Usuario();
    private UsuarioBO usuarioBO = new UsuarioBO();
    private UsuarioGrupoUsuarioBO usuarioGrupoUsuarioBO = new UsuarioGrupoUsuarioBO();
    /**
     * Creates new form TelaUsuariosForm
     */
    public TelaUsuariosForm() {
        initComponents();
        
        this.verificaALteracaoCampos();
        
        this.telaVazia();
    }

    TelaUsuariosForm(Usuario userSelecionado) {
        initComponents();
        
        this.atualizaUsuario( userSelecionado);

        this.preencheCampos( usuario);
        
        this.bloqueiaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblNomeTelaUsuarios = new javax.swing.JLabel();
        txtNomeTelaUsuarios = new javax.swing.JTextField();
        lblLoginTelaUsuarios = new javax.swing.JLabel();
        lblSenhaTelaUsuarios = new javax.swing.JLabel();
        txtSenhaTelaUsuarios = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        cbxCompras = new javax.swing.JCheckBox();
        cbxGerente = new javax.swing.JCheckBox();
        cbxEstoque = new javax.swing.JCheckBox();
        cbxCaixeiro = new javax.swing.JCheckBox();
        btnFecharTelaUsuario = new javax.swing.JButton();
        btnNovoTelaUsuario = new javax.swing.JButton();
        btnPesquisarTelaUsuario = new javax.swing.JButton();
        btnSalvarTelaUsuario = new javax.swing.JButton();
        btnExcluirTelaUsuario = new javax.swing.JButton();
        txtLoginTelaUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Usuários");

        lblNomeTelaUsuarios.setText("Nome: ");

        lblLoginTelaUsuarios.setText("Login: ");

        lblSenhaTelaUsuarios.setText("Senha: ");

        txtSenhaTelaUsuarios.setMinimumSize(new java.awt.Dimension(2, 8));
        txtSenhaTelaUsuarios.setSelectionEnd(8);
        txtSenhaTelaUsuarios.setVerifyInputWhenFocusTarget(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)), "Grupo de Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        cbxCompras.setText("Gestor de Compras");

        cbxGerente.setText("Gerente");

        cbxEstoque.setText("Gestor de Estoque");

        cbxCaixeiro.setText("Caixeiro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxGerente)
                    .addComponent(cbxEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxCompras)
                    .addComponent(cbxCaixeiro))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCompras)
                    .addComponent(cbxGerente))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEstoque)
                    .addComponent(cbxCaixeiro))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnFecharTelaUsuario.setText("Fechar");
        btnFecharTelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharTelaUsuarioActionPerformed(evt);
            }
        });

        btnNovoTelaUsuario.setText("Novo");
        btnNovoTelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoTelaUsuarioActionPerformed(evt);
            }
        });

        btnPesquisarTelaUsuario.setText("Pesquisar");
        btnPesquisarTelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarTelaUsuarioActionPerformed(evt);
            }
        });

        btnSalvarTelaUsuario.setText("Salvar");
        btnSalvarTelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTelaUsuarioActionPerformed(evt);
            }
        });

        btnExcluirTelaUsuario.setText("Excluir");
        btnExcluirTelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTelaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnNovoTelaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarTelaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarTelaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirTelaUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFecharTelaUsuario)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginTelaUsuarios, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNomeTelaUsuarios, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(txtLoginTelaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSenhaTelaUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenhaTelaUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNomeTelaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeTelaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeTelaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaTelaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenhaTelaUsuarios)
                    .addComponent(txtLoginTelaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginTelaUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharTelaUsuario)
                    .addComponent(btnSalvarTelaUsuario)
                    .addComponent(btnPesquisarTelaUsuario)
                    .addComponent(btnNovoTelaUsuario)
                    .addComponent(btnExcluirTelaUsuario))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarTelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTelaUsuarioActionPerformed
        try {
            boolean status = btnNovoTelaUsuario.isEnabled();
            
            usuario.setCodido(-1);
            String login = usuario.getLogin();
          
            this.recumperaCamposCadastro();
            
            
            if( status != true && usuarioBO.verificaLoginCadastrado(login)  == true)
                login = usuario.getLogin();
            
                usuario.setCodido( usuarioBO.cadastrarUsuario( usuario, login));
        
                if( usuario.getCodido() >=0){
                    if( usuarioGrupoUsuarioBO.verificaCadastrarUsuarioGrupoUsuario(usuario , usuario.getGrupoUsuarios()) == true){
                        JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!!", "Tela de usuário", JOptionPane.INFORMATION_MESSAGE);
                        this.telaAtualizada();
                        this.limpaCampos();
                    }else{
                        JOptionPane.showMessageDialog(this, "Falha no cadastro do grupo!!", "Tela de usuário", JOptionPane.ERROR_MESSAGE);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Falha no cadastro do usuário!!", "Tela de usuário", JOptionPane.ERROR_MESSAGE);
                }           
          
        } catch (UsuarioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Tela de usuário", JOptionPane.ERROR_MESSAGE);
             ex.printStackTrace();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Falha no cadastro do usuário!!", "Tela de usuário", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarTelaUsuarioActionPerformed

    private void btnExcluirTelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTelaUsuarioActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir este usuário?", "Exclusão de usuário", JOptionPane.YES_NO_OPTION);
        String login = txtLoginTelaUsuario.getText().trim();
          
        try {
            if( opcao == JOptionPane.YES_OPTION){
                if( usuarioBO.excluirUsuario( login) == true){
                    JOptionPane.showMessageDialog(this, "Usuário excluido com sucesso!!", "Exlusão de usuário", JOptionPane.INFORMATION_MESSAGE);
                    this.telaVazia();
                }else{
                    JOptionPane.showMessageDialog(this, "Usuário não excluido!!", "Exlusão de usuário", JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Falha no cadastro do usuário!!", "Tela de usuário", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnExcluirTelaUsuarioActionPerformed

    private void btnNovoTelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTelaUsuarioActionPerformed
       
        boolean status = true;
        String nome = txtNomeTelaUsuarios.getText().trim(), login = txtLoginTelaUsuario.getText().trim(), senha = new String( txtSenhaTelaUsuarios.getPassword()).trim();
        
        if( !login.equals("") || !nome.equals("") || !senha.equals("")){
            int opcao = JOptionPane.showConfirmDialog(this, "Se continuar haverá perda de dados.", "Deseja continuar ?", JOptionPane.YES_NO_OPTION);
            
            
            if( opcao == JOptionPane.NO_OPTION){
                status = false;
            }
        }
        
        if( status == true){
            this.bloqueiaCampos();
            this.limpaCampos();
        }
    }//GEN-LAST:event_btnNovoTelaUsuarioActionPerformed

    private void btnFecharTelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharTelaUsuarioActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair do sistema?", "Sair do sistema", JOptionPane.YES_NO_OPTION);
        if( opcao == 0)
            this.dispose();
    }//GEN-LAST:event_btnFecharTelaUsuarioActionPerformed

    private void btnPesquisarTelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarTelaUsuarioActionPerformed
        
        String nome = txtNomeTelaUsuarios.getText().trim(), login = txtLoginTelaUsuario.getText().trim(), senha = new String( txtSenhaTelaUsuarios.getPassword()).trim();
        boolean status = true;
        
        
        try {
            if( !nome.equals("") || !senha.equals("")){
               int opcao = JOptionPane.showConfirmDialog(this, "Se continuar haverá perda de dados" ,"Deseja continuar?", JOptionPane.YES_NO_OPTION);
               
               if( opcao == JOptionPane.NO_OPTION)
                   status = false;
            }
            
            
            if( status == true){
                if( !login.equals("")){
                    usuario = usuarioBO.buscarUsuarioLogin( login);
                                      
                    this.preencheCampos( usuario);
                    this.telaAtualizada();
                    
                } else if( !nome.equals("")){
                    usuario = usuarioBO.buscarUsuarioNome( nome);
                     this.preencheCampos( usuario);
                     this.telaAtualizada();
                }else
                    throw new UsuarioPesquisaInvalidaException();
                  
            }
            
        } catch (UsuarioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Tela de usuario", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Falha na cononexao com o banco.\n"+ex.getMessage(), "Tela de usuario", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPesquisarTelaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuariosForm().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirTelaUsuario;
    private javax.swing.JButton btnFecharTelaUsuario;
    private javax.swing.JButton btnNovoTelaUsuario;
    private javax.swing.JButton btnPesquisarTelaUsuario;
    private javax.swing.JButton btnSalvarTelaUsuario;
    private javax.swing.JCheckBox cbxCaixeiro;
    private javax.swing.JCheckBox cbxCompras;
    private javax.swing.JCheckBox cbxEstoque;
    private javax.swing.JCheckBox cbxGerente;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLoginTelaUsuarios;
    private javax.swing.JLabel lblNomeTelaUsuarios;
    private javax.swing.JLabel lblSenhaTelaUsuarios;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtLoginTelaUsuario;
    private javax.swing.JTextField txtNomeTelaUsuarios;
    private javax.swing.JPasswordField txtSenhaTelaUsuarios;
    // End of variables declaration//GEN-END:variables

    private void recumperaCamposCadastro() throws UsuarioException {
        GrupoUsuarios grupoUsuarios = new GrupoUsuarios();
        boolean status = false;
        
        String nome = txtNomeTelaUsuarios.getText().trim();
        if( !nome.equals(""))
            if( nome.length() <= 60)
                usuario.setNome( nome);
            else
                throw new UsuarioNomeGrandeException();
        else 
            throw new UsuarioCampoNomeVazioException();
        
        String login = txtLoginTelaUsuario.getText().trim();
        if( !login.equals(""))
            if( login.length() <= 8)
                usuario.setLogin( login);
            else 
                throw new UsuarioLoginGrandeException();
        else
            throw new UsuarioCampoLoginVazioException();
        
        String senha = new String( txtSenhaTelaUsuarios.getPassword() ).trim();
        if( !senha.equals( ""))
            if( senha.length() <= 8)
                usuario.setSenha( senha);
            else
                throw new UsuarioSenhaGrandeException();
        else
            throw new UsuarioCampoSenhaVazioException();
        
        this.verificaCaracteresLoginSenha( login, senha);
        
        if( this.cbxGerente.isSelected() == true){
            grupoUsuarios.setGerente( true);
            status = true;
        }
        
        if( this.cbxCompras.isSelected() == true){
            grupoUsuarios.setGestorCompras( true);
            status = true;
        }
        
        if( this.cbxEstoque.isSelected() == true){
            grupoUsuarios.setGestorEstoque(true);
            status = true;
        }
        
        if( this.cbxCaixeiro.isSelected() == true){
            grupoUsuarios.setCaixeiro(true);
            status = true;
        }
        
        if( status == false)
            throw new UsuarioGrupoNaoSelecionadoException();
        else
            this.usuario.setGrupoUsuarios( grupoUsuarios);
    }

    private void bloqueiaCampos() {
        this.btnExcluirTelaUsuario.setEnabled( false);
        this.btnPesquisarTelaUsuario.setEnabled( false);
        this.btnNovoTelaUsuario.setEnabled( false);
        this.btnSalvarTelaUsuario.setEnabled( true);
    }

    private void limpaCampos() {
        this.txtLoginTelaUsuario.setText("");
        this.txtNomeTelaUsuarios.setText("");
        this.txtSenhaTelaUsuarios.setText("");
        this.cbxGerente.setSelected( false);
        this.cbxCompras.setSelected( false);
        this.cbxEstoque.setSelected( false);
        this.cbxCaixeiro.setSelected( false);
    }

    private void telaVazia() {
        this.btnSalvarTelaUsuario.setEnabled( false);
        this.btnExcluirTelaUsuario.setEnabled( false);
        this.btnSalvarTelaUsuario.setEnabled( false);
        this.btnNovoTelaUsuario.setEnabled( false);
        this.limpaCampos();
    }

    private void preencheCampos( Usuario usuarioNew) {
       
        this.txtLoginTelaUsuario.setText( usuarioNew.getLogin());
        this.txtNomeTelaUsuarios.setText( usuarioNew.getNome());
        this.txtSenhaTelaUsuarios.setText( usuarioNew.getSenha());
        
        if( usuarioNew.getGrupoUsuarios().getGerente() == true){
            this.cbxGerente.setSelected(true);
        }else{
            this.cbxGerente.setSelected(false);
        }
        
        if( usuarioNew.getGrupoUsuarios().getGestorCompras()== true){
            this.cbxCompras.setSelected( true);
        }else{
            this.cbxCompras.setSelected( false);
        }
        
        if( usuarioNew.getGrupoUsuarios().getGestorEstoque()== true){
            this.cbxEstoque.setSelected( true);
        }else{
            this.cbxEstoque.setSelected( false);
        }
        
       if( usuarioNew.getGrupoUsuarios().getCaixeiro()== true){
            this.cbxCaixeiro.setSelected( true);
        }else{
           this.cbxCaixeiro.setSelected( false);
       }
    }

    private void telaAtualizada() {
        this.btnExcluirTelaUsuario.setEnabled( true);
        this.btnPesquisarTelaUsuario.setEnabled( true);
        this.btnNovoTelaUsuario.setEnabled( true);
        this.btnSalvarTelaUsuario.setEnabled( false);
    }

    private void verificaALteracaoCampos() {
        try{

           txtSenhaTelaUsuarios.addKeyListener( new KeyAdapter() {
                public void keyReleased( KeyEvent evento){
                    String senha = new String( txtSenhaTelaUsuarios.getPassword()).trim();
                    String login = txtLoginTelaUsuario.getText().trim();
                    String nome = txtNomeTelaUsuarios.getText().trim();
                    if( (!login.trim().equals("") && !nome.trim().equals("") && !senha.trim().equals(""))  
                            && (!login.trim().equals( usuario.getLogin().trim()) || !nome.trim().equals( usuario.getNome().trim()) 
                            || !senha.trim().equals( usuario.getSenha().trim())))
                                btnSalvarTelaUsuario.setEnabled( true);
                    else
                     btnSalvarTelaUsuario.setEnabled( false);
                }
            } );
           
           txtLoginTelaUsuario.addKeyListener( new KeyAdapter() {
                public void keyReleased( KeyEvent evento){
                    String senha = new String( txtSenhaTelaUsuarios.getPassword()).trim();
                    String login = txtLoginTelaUsuario.getText().trim();
                    String nome = txtNomeTelaUsuarios.getText().trim();

                    if( (!login.trim().equals("") && !nome.trim().equals("") && !senha.trim().equals(""))  
                            && (!login.trim().equals( usuario.getLogin().trim()) || !nome.trim().equals( usuario.getNome().trim()) 
                            || !senha.trim().equals( usuario.getSenha().trim())))
                                btnSalvarTelaUsuario.setEnabled( true);
                    else
                     btnSalvarTelaUsuario.setEnabled( false);
                }
            } );
           
           txtNomeTelaUsuarios.addKeyListener( new KeyAdapter() {
                public void keyReleased( KeyEvent evento){
                    String senha = new String( txtSenhaTelaUsuarios.getPassword()).trim();
                    String login = txtLoginTelaUsuario.getText().trim();
                    String nome = txtNomeTelaUsuarios.getText().trim();

                    if( (!login.trim().equals("") && !nome.trim().equals("") && !senha.trim().equals(""))  
                            && (!login.trim().equals( usuario.getLogin().trim()) || !nome.trim().equals( usuario.getNome().trim()) 
                            || !senha.trim().equals( usuario.getSenha().trim())))
                                btnSalvarTelaUsuario.setEnabled( true);
                    else
                     btnSalvarTelaUsuario.setEnabled( false);
                }
            } );
           
        }catch( NullPointerException ex){
            
        }
        
    }
    
    private void verificaCaracteresLoginSenha(String login, String senha) throws UsuarioException {
        
        for( int i = 0; i< login.length(); i+=1)
            if( (login.charAt(i) > 'Z' && login.charAt(i) > 'A') && (login.charAt(i) > 'z' && login.charAt(i) > 'a') && (login.charAt(i) > '0' && login.charAt(i) > '9'))
                throw new UsuarioCaractereInvalidoLogin();
        
        for( int i = 0; i< senha.length(); i+=1)
            if( (senha.charAt(i) > 'Z' && senha.charAt(i) > 'A') && (senha.charAt(i) > 'z' && senha.charAt(i) > 'a') && (senha.charAt(i) > '0' && senha.charAt(i) > '9'))
                throw new UsuarioCaractereInvalidoSenhaException();
                
    }

    private void atualizaUsuario(Usuario userSelecionado) {
        this.usuario.setLogin( userSelecionado.getLogin());
        this.usuario.setNome(userSelecionado.getNome());
        this.usuario.setSenha(userSelecionado.getSenha());
        this.usuario.setGrupoUsuarios( userSelecionado.getGrupoUsuarios());
    }

}
